{
 "title": "PFSense - VPN",
 "time": { "from": "now/d", "to": "now/d" },
 "panels": [
  {
   "title": "Number of monitored tunnels",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "IPSec" },
     "functions": [
      {
       "added": false,
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "sum",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "2m" ],
       "text": "sum(2m)"
      },
      {
       "added": false,
       "def": {
        "category": "Transform",
        "defaultParams": [
         "1m",
         "avg"
        ],
        "name": "groupBy",
        "params": [
         { "name": "interval", "type": "string" },
         {
          "name": "function",
          "options": [
           "avg",
           "min",
           "max",
           "sum",
           "count",
           "median"
          ],
          "type": "string"
         }
        ]
       },
       "params": [
        "2m",
        "median"
       ],
       "text": "groupBy(2m, median)"
      }
     ],
     "host": { "filter": "pfsenseAZc-Slave" },
     "item": { "filter": "/.*Tunnel.*/" },
     "options": {
      "showDisabledItems": false
     },
     "rawSql": "select count(name) from items WHERE key_ like '%ipsec.tunnel%con%';\n",
     "slaProperty": { "name": "SLA", "property": "sla" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 4
     }
    }
   ]
  },
  {
   "title": "Number of VPN issues",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "application": { "filter": "IPSec" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "pfsenseAZc-Slave" },
     "item": { "filter": "" },
     "mode": 4,
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 4
     }
    }
   ]
  },
  {
   "title": "Current VPN issues",
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 3 },
   "targets": {
    "zabbix_prd": {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    "zabbix_prd_api": {
     "application": { "filter": "IPSec" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "/.*pfsense.*/" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   }
  },
  {
   "title": "Packets",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "IPSec" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "pfsenseAZc-Slave" },
     "item": { "filter": "/.*PKTS.*/" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Traffic (bytes)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "application": { "filter": "IPSec" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "pfsenseAZc-Slave" },
     "item": { "filter": "/.*Bytes.*/" },
     "options": {
      "showDisabledItems": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}